services:
    app.exception_listener:
        class: AppBundle\EventListener\ExceptionListener
        arguments:
            - "%kernel.environment%"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }